package stocksNames

import (
	"github.com/stock-monitor/internal/stockParser"
	"time"
)
var StocksLite = []stockParser.Stock{
	{"Apple", "AAPL", time.Now()},
}
var Stocks = []stockParser.Stock{
	{"Apple", "AAPL", time.Now()},
	{"Adobe","ADBE", time.Now()},
	{"Autodesk", "ADSK", time.Now()},
	{"AMD", "AMD", time.Now()},
	{"Arista","ANET",  time.Now()},
	{"Broadcom","AVGO",time.Now()},
	{"Booking", "BKNG",time.Now() },
	{"Check Point", "CHKP", time.Now()},
	{"salesforce","CRM", time.Now()},
	{"Cisco","CSCO", time.Now()},
	{"Citrix","CTXS", time.Now()},
	{"Dropbox","DBX", time.Now()},
	{"DELL","DELL", time.Now()},
	{"EPAM", "EPAM",time.Now()},
	{"F5 Networks","FFIV", time.Now()},
	{"GoDaddy","GDDY", time.Now()},
	{"Hewlett Packard","HPE", time.Now()},
	{"IBM", "IBM",time.Now()},
	{"INTEL","INTC", time.Now()},
	{"Juniper Networks","JNPR", time.Now()},
	{"Mastercard", "MA", time.Now()},
	{"MongoDB", "MDB",time.Now()},
	{"Microsoft", "MSFT",time.Now()},
	{"Motorolla", "MSI", time.Now()},
	{"Cloudflare", "NET",time.Now()},
	{"Nokia", "NOK",time.Now()},
	{"NETGEAR", "NTGR",time.Now()},
	{"NVIDIA", "NVDA",time.Now()},
	{"Oracle", "ORCL",time.Now()},
	{"Palo Alto", "PANW", time.Now()},
	{"PagerDuty", "PD",time.Now()},
	{"PayPal", "PYPL",time.Now()},
	{"QUALCOMM", "QCOM",time.Now()},
	{"Qualys", "QLYS",time.Now()},
	{"Rapid7", "RPD",time.Now()},
	{"Seagate", "STX",time.Now()},
	{"SolarWinds", "SWI",time.Now()},
	{"Tenable", "TENB",time.Now()},
	{"Twilio", "TWLO",time.Now()},
	{"Ubiquiti", "UI",time.Now()},
	{"Visa", "V", time.Now()},
	{"Vmware", "VMW", time.Now()},
	{"Slack", "WORK", time.Now()},
	{"XEROX", "XRX", time.Now()},
	{"ZOOM", "ZM", time.Now()},
	{"Activision Blizzard", "ATVI",  time.Now()},
	{"The Walt Disney Company", "DIS",  time.Now()},
	{"GOOGL1", "GOOGL",  time.Now()},
	{"GOOGL2",  "GOOG", time.Now()},
	{"Amazon", "AMZN",  time.Now()},
	{"Yandex", "YNDX",  time.Now()},
	{"FXIT", "FXIT.NX",  time.Now()},
	{"Facebook", "FB",  time.Now()},
	{"Electronics Arts", "EA",  time.Now()},
	{"Netflix", "NFLX", time.Now()},
	{"Pinterest",  "PINS", time.Now()},
	{"Spotify", "SPOT",  time.Now()},
	{"TripAdviso", "TRIP", time.Now()},
}